/**
 * @fileoverview Authentication controller handling user registration, login, and profile retrieval.
 *
 * This controller provides HTTP endpoints for:
 * - User registration with validation
 * - User authentication (login)
 * - Current user profile retrieval
 *
 * All endpoints return standardized JSON responses with appropriate HTTP status codes.
 * Authentication is handled via JWT tokens generated by the auth service.
 *
 * @module controllers/auth
 */

import { Request, Response } from 'express'
import { authService } from '../services/auth.js'
import { AuthRequest } from '../middleware/auth.js'
import { AppError, isAppError, HttpStatus } from '../utils/errors.js'

/**
 * Authentication controller providing request handlers for auth-related endpoints.
 *
 * @example
 * // Route setup
 * router.post('/register', authController.register);
 * router.post('/login', authController.login);
 * router.get('/me', authenticate, authController.me);
 */
export const authController = {
  /**
   * Registers a new user account.
   *
   * Validates that all required fields are provided and password meets
   * minimum length requirements before delegating to the auth service.
   *
   * @param {Request} req - Express request object
   * @param {string} req.body.email - User's email address
   * @param {string} req.body.name - User's display name
   * @param {string} req.body.password - User's password (min 6 characters)
   * @param {Response} res - Express response object
   *
   * @returns {Promise<void>} Sends JSON response with user data and token
   *
   * @throws {AppError} 400 - If required fields are missing
   * @throws {AppError} 400 - If password is less than 6 characters
   * @throws {AppError} 409 - If email is already registered (from service)
   *
   * @example
   * // Request
   * POST /api/auth/register
   * {
   *   "email": "user@example.com",
   *   "name": "John Doe",
   *   "password": "securepass123"
   * }
   *
   * // Success Response (201 Created)
   * {
   *   "user": {
   *     "id": "clx...",
   *     "email": "user@example.com",
   *     "name": "John Doe",
   *     "createdAt": "2024-01-15T10:30:00.000Z"
   *   },
   *   "token": "eyJhbGciOiJIUzI1NiIs..."
   * }
   *
   * // Error Response (400 Bad Request)
   * { "message": "Email, name, and password are required" }
   */
  async register(req: Request, res: Response) {
    try {
      const { email, name, password } = req.body

      if (!email || !name || !password) {
        throw AppError.validation('Email, name, and password are required', {
          fields: { email: !email, name: !name, password: !password },
        })
      }

      if (password.length < 6) {
        throw AppError.validation('Password must be at least 6 characters', {
          field: 'password',
          minLength: 6,
        })
      }

      const result = await authService.register({ email, name, password })
      res.status(HttpStatus.CREATED).json(result)
    } catch (error) {
      if (isAppError(error)) {
        res.status(error.statusCode).json({ message: error.message })
        return
      }
      const message = error instanceof Error ? error.message : 'Registration failed'
      res.status(HttpStatus.BAD_REQUEST).json({ message })
    }
  },

  /**
   * Authenticates a user with email and password.
   *
   * Validates credentials are provided, then delegates to auth service
   * for verification and token generation.
   *
   * @param {Request} req - Express request object
   * @param {string} req.body.email - User's email address
   * @param {string} req.body.password - User's password
   * @param {Response} res - Express response object
   *
   * @returns {Promise<void>} Sends JSON response with user data and token
   *
   * @throws {AppError} 400 - If email or password is missing
   * @throws {AppError} 401 - If credentials are invalid (from service)
   *
   * @example
   * // Request
   * POST /api/auth/login
   * {
   *   "email": "user@example.com",
   *   "password": "securepass123"
   * }
   *
   * // Success Response (200 OK)
   * {
   *   "user": {
   *     "id": "clx...",
   *     "email": "user@example.com",
   *     "name": "John Doe",
   *     "createdAt": "2024-01-15T10:30:00.000Z"
   *   },
   *   "token": "eyJhbGciOiJIUzI1NiIs..."
   * }
   *
   * // Error Response (401 Unauthorized)
   * { "message": "Invalid credentials" }
   */
  async login(req: Request, res: Response) {
    try {
      const { email, password } = req.body

      if (!email || !password) {
        throw AppError.validation('Email and password are required', {
          fields: { email: !email, password: !password },
        })
      }

      const result = await authService.login({ email, password })
      res.json(result)
    } catch (error) {
      if (isAppError(error)) {
        res.status(error.statusCode).json({ message: error.message })
        return
      }
      const message = error instanceof Error ? error.message : 'Login failed'
      res.status(HttpStatus.UNAUTHORIZED).json({ message })
    }
  },

  /**
   * Retrieves the currently authenticated user's profile.
   *
   * Requires a valid JWT token in the Authorization header.
   * The user ID is extracted from the token by the auth middleware.
   *
   * @param {AuthRequest} req - Express request with authenticated user ID
   * @param {string} req.userId - User ID extracted from JWT token
   * @param {Response} res - Express response object
   *
   * @returns {Promise<void>} Sends JSON response with user profile
   *
   * @throws {AppError} 401 - If user is not authenticated (no userId)
   * @throws {AppError} 404 - If user record not found in database
   * @throws {AppError} 500 - If database query fails
   *
   * @example
   * // Request
   * GET /api/auth/me
   * Authorization: Bearer eyJhbGciOiJIUzI1NiIs...
   *
   * // Success Response (200 OK)
   * {
   *   "id": "clx...",
   *   "email": "user@example.com",
   *   "name": "John Doe",
   *   "createdAt": "2024-01-15T10:30:00.000Z"
   * }
   *
   * // Error Response (401 Unauthorized)
   * { "message": "Not authenticated" }
   *
   * // Error Response (404 Not Found)
   * { "message": "User not found" }
   */
  async me(req: AuthRequest, res: Response) {
    try {
      if (!req.userId) {
        throw AppError.unauthorized('Not authenticated')
      }

      const user = await authService.getUser(req.userId)
      if (!user) {
        throw AppError.notFound('User', req.userId)
      }

      res.json(user)
    } catch (error) {
      if (isAppError(error)) {
        res.status(error.statusCode).json({ message: error.message })
        return
      }
      res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({ message: 'Failed to get user' })
    }
  },
}
